apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: yvmis50bo-nodejs 
  janus-idp.io/tekton: yvmis50bo-nodejs
  backstage.io/kubernetes-id: yvmis50bo-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yvmis50bo-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml