apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yvmis50bo-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yvmis50bo-nodejs 
  name: yvmis50bo-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: yvmis50bo-nodejs 
